# Generated by Django 4.0.3 on 2023-01-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_post_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
