# Generated by Django 4.0.3 on 2023-01-28 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_blogcomment_delete_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogComment',
        ),
    ]
